### ISSUE TITLE
Dynamically adding tools does not properly handle Share Context

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#259] opened 2024-08-22 21:34 UTC
Best example of this is the knowledge tool, which has this line:
```
Share Context: github.com/gptscript-ai/context/workspace
```

Grant put together tests here:
'https://github.com/g-linville/context-testing

Follow up question: does Share Tools work? seems like it does, but we should verify

**Comment by sangee2004** [comment] 2024-08-22 22:01
This is one of the workflows were we see the `Share Context` not working when knowledge tool is added using `Add Knowledge` option.

1. Create an assistant with no tools.
2. Chat with the assistant and use `Add Knowledge` to add a knowledge file.
3. Try to ask any question relating to knowledge file like say `How to raise money to start a Business "
4. Notice that knowledge tool will not get called unless we explicitly ask it to use knowledge like - `How to raise money to start a Business . Use knowledge."`

This behavior of needing to ask it to explicitly use `knowledge` tool is not needed if I have `workspace` tool added to the assistant. 
This should not needed since we already have  `Share Context: github.com/gptscript-ai/context/workspace` included in `knowledge` tool.

**Comment by cjellick** [comment] 2024-08-23 15:37
I'm assigning to myself because I guess the best way forward with this is, as @thedadams mentioned, to support dynamic tool adding in core gptscript. So, I'll talk to @ibuildthecloud about this on monday and see where he wants to go with it.

**Comment by cjellick** [comment] 2024-08-27 22:55
fixed in core gptscript here: https://github.com/gptscript-ai/gptscript/pull/827

**Comment by sangee2004** [comment] 2024-08-27 23:50
Testing desktop app with gptscript version - `v0.0.0-dev+f2bfa9f3`

I am still able to reproduce the issue with having to ask Knowledge tool to used explicitly when testing the scenario outlined in  https://github.com/gptscript-ai/desktop/issues/259#issuecomment-2305824276

I will also test cases mentioned in https://github.com/g-linville/context-testing

**Comment by sangee2004** [comment] 2024-08-29 04:53
When testing scenarios by adding the tools dynamically to a thread using "Add Tool" from https://github.com/g-linville/context-testing , following are the observations made:

1. github.com/g-linville/context-testing/direct - Fail - Not able to see the context tool
2. github.com/g-linville/context-testing/indirect - Fail - Not able to see the context tool
3. github.com/g-linville/context-testing/sharedirect - Pass
4. github.com/g-linville/context-testing/sharedirect - Pass

When adding tool - `github.com/g-linville/context-testing/direct`
![Image](https://github.com/user-attachments/assets/50fe4b60-a74f-483b-96cc-a112f4cdb3ae)


When adding tool - `github.com/g-linville/context-testing/indirect`
![Image](https://github.com/user-attachments/assets/244e57dc-c62b-4520-9f50-ff2452c451f6)

**Comment by thedadams** [comment] 2024-08-30 04:37
In the case of `github.com/g-linville/context-testing/direct`, the assistant doesn't have "direct" access to the context. Only the tool `blue` does because the context is not shared. Therefore, the context is only run when the `blue` tool is run.

For example:
<img width="926" alt="Screenshot 2024-08-30 at 00 32 27" src="https://github.com/user-attachments/assets/c7f75f4d-8d5d-4138-8747-ca55f9adc714">


Similarly for the `https://github.com/g-linville/context-testing/indirect` tool:
<img width="934" alt="Screenshot 2024-08-30 at 00 33 56" src="https://github.com/user-attachments/assets/c3716408-aa86-48ce-a659-73d7a026e545">


Let me know what you think about these results.

**Comment by sangee2004** [comment] 2024-09-12 20:51
Closing this issue as per testing based on  https://github.com/gptscript-ai/desktop/issues/259#issuecomment-2320021127.

**Closed by sangee2004** 2024-09-12 20:51 UTC
Labels: bug
