### ISSUE TITLE
Threads relating to deleted assistants are stuck in loading state with assistant name as "Tildy"

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#266] opened 2024-08-23 00:13 UTC
Electron build - `0bdee033a02`

**Steps to reproduce the problem:**
1. Create an assistant.
2. Chat with the assistant and have some conversation.
3. Delete the assistant.

Notice that the threads relating to this assistant now shows up with assistant name as "Tildy" and is stuck in "loading" state near the chat message field.

<img width="1265" alt="Screenshot 2024-08-22 at 5 08 27 PM" src="https://github.com/user-attachments/assets/27d87556-e277-4dfc-ba22-2301b7c6a189">

**Comment by thedadams** [comment] 2024-08-23 23:08
This is essentially a duplicate of https://github.com/gptscript-ai/desktop/issues/90 (although the outcome has changed since this issue was created).

We need to do something intelligent with threads where the assistant has been deleted.

**Comment by cjellick** [comment] 2024-08-27 23:00
Im going to close this as a dupe of #90

**Closed by cjellick** 2024-08-27 23:00 UTC
Labels: bug
